name: Deploy Homepage Service to Google Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: dipeshsingh2012/shared-workflows/.github/workflows/deploy-cloud-run.yml@main
    with:
      service_name: 'homepage-service'
      port: 8002
      health_check_path: '/api/v1/health'
